name: giaohang_workspace
description: Workspace cho Delivery App và Operations Web.
publish_to: none

environment:
  sdk: ^3.9.0

workspace:
  - apps/delivery_app
  - apps/operations_web
  - packages/giaohang_config
  - packages/giaohang_design
  - packages/giaohang_domain
